version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    open-pull-requests-limit: 25
    schedule:
      interval: "monthly"
    groups:
      maven-dependencies:
        patterns:
          - "*"
          
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    groups:
      ci-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    groups:
      docker-dependencies:
        patterns:
          - "*"
